//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.42
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNuke.Modules.Store.WebControls {
    
    
    /// <summary>
    /// Classe CustomerOrders.
    /// </summary>
    /// <remarks>
    /// Classe générée automatiquement.
    /// </remarks>
    public partial class CustomerOrders {
        
        /// <summary>
        /// Contrôle lblPaymentError.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPaymentError;
        
        /// <summary>
        /// Contrôle plhGrid.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder plhGrid;
        
        /// <summary>
        /// Contrôle lblError.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblError;
        
        /// <summary>
        /// Contrôle grdOrders.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DataGrid grdOrders;
        
        /// <summary>
        /// Contrôle plhForm.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder plhForm;
        
        /// <summary>
        /// Contrôle lblEditTitle.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEditTitle;
        
        /// <summary>
        /// Contrôle pnlOrderDetails.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlOrderDetails;
        
        /// <summary>
        /// Contrôle lblDetailsError.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblDetailsError;
        
        /// <summary>
        /// Contrôle detailsTable.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable detailsTable;
        
        /// <summary>
        /// Contrôle lblOrderNumberTag.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblOrderNumberTag;
        
        /// <summary>
        /// Contrôle lblOrderDateTag.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblOrderDateTag;
        
        /// <summary>
        /// Contrôle TD1.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell TD1;
        
        /// <summary>
        /// Contrôle lblShipDateTag.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblShipDateTag;
        
        /// <summary>
        /// Contrôle lblOrderStatusTag.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblOrderStatusTag;
        
        /// <summary>
        /// Contrôle lblOrderNumber.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblOrderNumber;
        
        /// <summary>
        /// Contrôle lblOrderDate.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblOrderDate;
        
        /// <summary>
        /// Contrôle TD2.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell TD2;
        
        /// <summary>
        /// Contrôle lblShipDate.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblShipDate;
        
        /// <summary>
        /// Contrôle lblOrderStatus.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblOrderStatus;
        
        /// <summary>
        /// Contrôle ddlOrderStatus.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlOrderStatus;
        
        /// <summary>
        /// Contrôle lnkbtnSave.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnkbtnSave;
        
        /// <summary>
        /// Contrôle lblBillingAddressTag.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblBillingAddressTag;
        
        /// <summary>
        /// Contrôle lblShippingAddressTag.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblShippingAddressTag;
        
        /// <summary>
        /// Contrôle btnPayViaPayPal.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnPayViaPayPal;
        
        /// <summary>
        /// Contrôle spanBR.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spanBR;
        
        /// <summary>
        /// Contrôle btnCancel.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnCancel;
        
        /// <summary>
        /// Contrôle lblBillTo.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblBillTo;
        
        /// <summary>
        /// Contrôle lblShipTo.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblShipTo;
        
        /// <summary>
        /// Contrôle grdOrderDetails.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DataGrid grdOrderDetails;
        
        /// <summary>
        /// Contrôle lblTotalTag.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalTag;
        
        /// <summary>
        /// Contrôle lblTotal.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotal;
        
        /// <summary>
        /// Contrôle lblPostageTag.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPostageTag;
        
        /// <summary>
        /// Contrôle lblPostage.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPostage;
        
        /// <summary>
        /// Contrôle trTax.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow trTax;
        
        /// <summary>
        /// Contrôle lblTaxTag.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTaxTag;
        
        /// <summary>
        /// Contrôle lblTax.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTax;
        
        /// <summary>
        /// Contrôle lblTotalIncPostageTag.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalIncPostageTag;
        
        /// <summary>
        /// Contrôle lblTotalIncPostage.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTotalIncPostage;
        
        /// <summary>
        /// Contrôle pnlPayPalTransfer.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlPayPalTransfer;
        
        /// <summary>
        /// Contrôle lblGoToPayPal.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblGoToPayPal;
        
        /// <summary>
        /// Contrôle btnGoToPayPal.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnGoToPayPal;
        
        /// <summary>
        /// Contrôle paypalimage2.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image paypalimage2;


        protected global::System.Web.UI.WebControls.Label lblOrderCompany;


        
    }
}
