//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.42
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNuke.Modules.Store.Cart {
    
    
    /// <summary>
    /// Classe AuthorizeNetPayment.
    /// </summary>
    /// <remarks>
    /// Classe générée automatiquement.
    /// </remarks>
    public partial class AuthorizeNetPayment {
        
        /// <summary>
        /// Contrôle lblPaymentTitle.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.UserControl lblPaymentTitle;
        
        /// <summary>
        /// Contrôle tr1.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow tr1;
        
        /// <summary>
        /// Contrôle lblCard.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCard;
        
        /// <summary>
        /// Contrôle rbCard.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButtonList rbCard;
        
        /// <summary>
        /// Contrôle rfvCard.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCard;
        
        /// <summary>
        /// Contrôle tr2.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow tr2;
        
        /// <summary>
        /// Contrôle lblName.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblName;
        
        /// <summary>
        /// Contrôle txtName.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtName;
        
        /// <summary>
        /// Contrôle rfvName.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvName;
        
        /// <summary>
        /// Contrôle lblCardNumber.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.UserControl lblCardNumber;
        
        /// <summary>
        /// Contrôle txtNumber.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtNumber;
        
        /// <summary>
        /// Contrôle rfvNumber.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNumber;
        
        /// <summary>
        /// Contrôle lblExpiryDate.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.UserControl lblExpiryDate;
        
        /// <summary>
        /// Contrôle ddlMonth.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlMonth;
        
        /// <summary>
        /// Contrôle lblSlash.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSlash;
        
        /// <summary>
        /// Contrôle ddlYear.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlYear;
        
        /// <summary>
        /// Contrôle lblCSC.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.UserControl lblCSC;
        
        /// <summary>
        /// Contrôle txtVer.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtVer;
        
        /// <summary>
        /// Contrôle rfvVer.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvVer;
        
        /// <summary>
        /// Contrôle litError.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litError;
        
        /// <summary>
        /// Contrôle lblConfirmMessage.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblConfirmMessage;
        
        /// <summary>
        /// Contrôle btnProcess.
        /// </summary>
        /// <remarks>
        /// Champ généré automatiquement.
        /// Pour changer, déplacez la déclaration du fichier du concepteur vers le fichier code-behind.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnProcess;
    }
}
